apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    cloudcustodian.io/azure-container-host: "cloud-custodian"
    cloudcustodian.io/azure-name: "{{ .Release.Name }}"
    {{ template "azureTargetSubscriptionLabel" . }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      cloudcustodian.io/azure-container-host: "cloud-custodian"
      cloudcustodian.io/azure-name: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        cloudcustodian.io/azure-container-host: "cloud-custodian"
        cloudcustodian.io/azure-name: "{{ .Release.Name }}"
        {{ template "azureTargetSubscriptionLabel" . }}
    spec:
      containers:
      - name: "{{ .Release.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.environment }}
        env: 
        {{- range $name, $value := .Values.environment }}
        - name: {{ $name }}
          value: {{ $value }}
        {{- end }}
        {{- end }}
        command: 
          - "/usr/local/bin/python3"
        args:
          - "-m"
          - "c7n_azure.container_host.host"
